# Generated by Django 5.1.2 on 2024-10-10 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('level_of_competence', models.CharField(choices=[('Начинаюйщи', 'Начинаюйщи'), ('Опытный', 'Опытный'), ('Называй меня - мастер', 'Называй меня - мастер')], default='', max_length=100, verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Сборщик',
                'verbose_name_plural': 'Сборщики',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('build_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сборки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('id_pc', models.IntegerField(unique=True, verbose_name='Номер ПК')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Изображение')),
                ('builder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='computer_hardware_store.builder', verbose_name='Сборщик')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU_model', models.CharField(max_length=50, verbose_name='Процессор')),
                ('computers', models.ManyToManyField(related_name='CPUs', to='computer_hardware_store.computer', verbose_name='Компьютеры')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
                'ordering': ['CPU_model'],
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPU_model', models.CharField(blank=True, max_length=200, verbose_name='Видеокарта')),
                ('computers', models.ManyToManyField(related_name='GPUs', to='computer_hardware_store.computer', verbose_name='Компьютеры')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
                'ordering': ['GPU_model'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('computer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='computer_hardware_store.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['amount', 'price'],
            },
        ),
    ]
